### PR TITLE
docs/attestation: use mermaid to render communications

### PR DESCRIPTION
**Pull request by osresearch**
image

Enable the mermaid plugin so that communication diagrams can be included in the markdown documentation.

### CODE REVIEW

**Comment by osresearch** [comment]
image

mermaid isn't perfect, although it seems to do a decent job of turning the text into diagrams.  One nice feature is that they are not images -- the diagrams are SVG so they will still show up in google searches or find-in-page functions.

**Comment by nicowilliams** [comment]
Nice!

**Comment by nicowilliams** [comment]
Does GH support this?  Looking at `docs/attestation.md` in this branch, it looks like it does not.

**Comment by osresearch** [comment]
unfortunately gh pages does not support it, so they don't render in the previews.  if you have a local checkout you can render them with:

```
pip3 install -r requirements.txt
mkdocs serve --dirtyreload
```

**Comment by osresearch** [comment]
I've gone ahead and merged this so that it will be visible and we can discuss where else we need diagrams.

**Pull request merged**
